window.ARTIST = {
  name: "Daria Avdeeva",
  email: "artist.dariaavd@gmail.com",
  instagram: "@dariadrawsart"
};

window.ARTWORKS = [
  {
    id: "a1",
    title: "Alfred on a Blue Bag",
    year: 2023,
    collection: "Portfolio",
    size_cm: "60x80",
    medium: "Oil on Canvas",
    status: "Available",
    price: "5000",
    image: "./images/Alfred_On_A_Blue_Bag.jpg",
    location: "Dubai",
    description: "Alfred on a Blue Bag is a captivating oil painting capturing the essence of feline anticipation. Alfred, the artist's cat, perches on a textured blue bag, a ball nestled between his paws. The artist's skillful rendering of Alfred's fur invites tactile exploration. Alfred's eager expression, directed towards the unseen owner, conveys anticipation, establishing a connection with the viewer. The blue bag, with its varied shades, creates a dynamic surface, complemented by strokes of yellow and orange in the background. This masterpiece blends texture, color, and emotion to evoke the shared experiences of pet ownership and companionship."
  },
  {
    id: "a2",
    title: "Aquatic Fantasy",
    year: 2023,
    collection: "Portfolio",
    size_cm: "80x80",
    medium: "Oil on Canvas",
    status: "Available",
    price: "2500",
    image: "./images/Aquatic_Fantasy.jpg",
    location: "Dubai",
    description: "In a world grappling with sustainability, Aquatic Fantasy emerges, urging collective responsibility. This abstract oil painting transports viewers into an underwater dreamscape, showcasing vibrant coral formations and diverse schools of fish. Symbolizing unity and interconnectedness, it prompts reflection on environmental preservation. Through its abstract nature, Aquatic Fantasy ignites conversations on sustainability and inspires a renewed commitment to stewardship. It serves as a potent reminder that through collective action, we can safeguard our oceans for future generations."
  },
  {
    id: "a3",
    title: "Bowl of Strawberries",
    year: 2024,
    collection: "Portfolio",
    size_cm: "40x50",
    medium: "Oil on Canvas",
    status: "Available",
    price: "3000",
    image: "./images/Bowl_Of_Strawberries.jpg",
    location: "Dubai",
    description: "A Bowl of Strawberries is a tender portrayal of simplicity and warmth. In this painting, a hand rests gently on a lap beside a bowl of strawberries. The artwork exudes a delicate and feminine aura, with soft and effortless strokes that seem to flow seamlessly, as if painted in one graceful breath. The atmosphere is airy and light, reminiscent of a summer day when strawberries are freshly picked—each stroke capturing the essence of that fleeting moment of sweetness and joy. It's a visual symphony of tranquility and nostalgia, inviting viewers to bask in the gentle embrace of nature's beauty and the simple pleasures of life."
  },
  {
    id: "a4",
    title: "Bowtie",
    year: 2022,
    collection: "Portfolio",
    size_cm: "80x60",
    medium: "Oil on Canvas",
    status: "Available",
    price: "5000",
    image: "./images/Bowtie.jpg",
    location: "Dubai",
    description: "Bowtie is a captivating oil portrait that deftly explores color, symbolism, and cultural nuances. The central figure, a young ginger man in a dark green blazer, captivates with his direct gaze. The focal point is a butterfly-shaped bowtie, imbued with linguistic subtleties across European languages. Vibrant orange hair against the dark blazer creates a striking contrast, echoed in the nuanced background palette. This interplay of warm and cool tones creates a harmonious yet dynamic composition. Bowtie not only adds whimsy but also prompts contemplation of cultural connotations, showcasing the artist's technical finesse in creating a multifaceted portrait."
  },
  {
    id: "a5",
    title: "Boxing Gloves",
    year: 2024,
    collection: "Portfolio",
    size_cm: "90x90",
    medium: "Oil on Canvas",
    status: "Available",
    price: "5000",
    image: "./images/Boxing_Gloves.png",
    location: "Dubai",
    description: "Boxing Gloves captures a moment of release and triumph. The silver boxing gloves and the black wraps are scattered around, traces of a fierce battle or intense practice. These objects echo a deeper narrative—of shedding rage and fear, of conquering inner battles. The neutral palette of blacks, greys, and beiges fosters a serene atmosphere, reflecting the calm after an adrenaline rush. It's a visual play of contrasts: the gleaming silver against muted tones, the random placement suggesting order found within chaos. Boxing Gloves invites viewers to feel the cathartic power of overcoming fears and embracing newfound strength."
  },
  {
    id: "a6",
    title: "By The Pool",
    year: 2023,
    collection: "Portfolio",
    size_cm: "60x50",
    medium: "Oil on Canvas",
    status: "Available",
    price: "5000",
    image: "./images/By_The_Pool.jpg",
    location: "Dubai",
    description: "By the Pool is an evocative oil painting capturing a sun-drenched moment of leisure. A young girl stands confidently in a vibrant blue swimsuit at the canvas's center, partially shaded from the noonday sun. The background, a subtle swimming pool tile pattern, blends harmoniously with her attire, creating visual unity. Dramatic contrasts in values emphasize the intensity of the sun, casting a slight sunburn on the girl. Her vibrant ginger hair serves as a bright focal point against the pool-blue surroundings, enhancing the painting's luminosity. The interplay of warm and cool tones immerses viewers in the sensation of a hot summer day, evoking the shimmering heat. With an aura of calmness and confidence, the composition invites viewers to share in the tranquil joy of the moment, celebrating the beauty of sunlight and leisure in a captivating, immersive experience."
  },
  {
    id: "a7",
    title: "Changes",
    year: 2023,
    collection: "Portfolio",
    size_cm: "90x60",
    medium: "Oil on Canvas",
    status: "Available",
    price: "5000",
    image: "./images/Changes.jpg",
    location: "Dubai",
    description: "Changes part of the ongoing series Paintings with Scars eloquently portrays a transformative journey of self-discovery and artistic evolution. Layering new paint over older works symbolizes the artist's metamorphosis from youth to maturity. The term scars refers to textures and scratches on the canvas—remnants of past challenges embraced rather than concealed. These imperfections coexist with new layers, forming a tapestry of beauty and resilience. Changes invites viewers to reflect on their own journeys, appreciating the value in marks left by time and experience. It stands as a visual metaphor for personal growth, empowering and inspiring all who encounter it."
  },
  {
    id: "a8",
    title: "Chasing Luck",
    year: 2023,
    collection: "Portfolio",
    size_cm: "120x90",
    medium: "Oil on Canvas",
    status: "Available",
    price: "8000",
    image: "./images/Chasing-Luck_res.jpg",
    location: "Dubai",
    description: "Chasing Luck captures the perpetual pursuit of fortune. Two dynamically posed bunnies engage in a playful, circular chase within a sunlit meadow. Each bunny mirrors the diverse forms luck can assume, as for each person the concept of luck is different. The meadow's vibrant movement, depicted through chaotic brushstrokes, lends an energetic quality. The interplay of textures and contrasts invites exploration of a timeless pursuit of elusive fortunes."
  },
  {
    id: "a9",
    title: "Clementine Branch",
    year: 2023,
    collection: "Portfolio",
    size_cm: "50x70",
    medium: "Oil on Canvas",
    status: "Available",
    price: "5000",
    image: "./images/Clementine_Branch.jpg",
    location: "Dubai",
    description: "In this painting duo, the citrus fruits have golden yellows echoing the sun's warmth, as well as shades of bright oranges and burnt browns. These warm tones intensify the summer heat and haze, creating an atmosphere that feels almost tangible. Dynamic brushstrokes add movement and energy, infusing the compositions with life. The contrast between the simple yet vivid fruits and the nuanced background creates a delicate interplay, inviting viewers to savor the sensory richness of a sun-kissed summer day."
  },
  {
    id: "a10",
    title: "Cobalt Peacock",
    year: 2023,
    collection: "Portfolio",
    size_cm: "76x76",
    medium: "Oil on Canvas",
    status: "Available",
    price: "5000",
    image: "./images/Cobalt_Peacock.jpg",
    location: "Dubai",
    description: "Cobalt Peacock showcases the artist's technical prowess in capturing the elegance and vibrancy of a blue peacock. Bold brushstrokes bring the majestic bird to life, accentuating its intricate plumage. Set against a golden yellow background, the peacock's regal presence is enhanced, creating a harmonious balance of contrasting colors. The dynamic portrayal of the peacock in mid-stride conveys movement and immediacy, while layers and glazes deepen shades and add richness to the colors. This meticulous technique enhances visual depth, resulting in a captivating piece that celebrates both the beauty of the peacock and the artist's mastery of layering and glazing."
  },
  {
    id: "a11",
    title: "Comfort Zone",
    year: 2023,
    collection: "Portfolio",
    size_cm: "70x80",
    medium: "Oil on Canvas",
    status: "Available",
    price: "5000",
    image: "./images/Comfort_Zone.jpg",
    location: "Dubai",
    description: "Comfort Zone is an evocative oil painting that delves into the beauty of embracing authenticity. It centers on a stack of plain white pillows on a deep indigo grey couch, creating a striking contrast. The muted color palette highlights the raw nature of the pillows, symbolizing unfiltered self-expression. The absence of pillow covers metaphorically represents shedding external layers to reveal one's true self. The painting celebrates self-acceptance, inviting viewers to appreciate the beauty of authenticity and find comfort in being unabashedly genuine."
  },
  {
    id: "a12",
    title: "Composition with Northern Mushrooms 1",
    year: 2022,
    collection: "Portfolio",
    size_cm: "60x60",
    medium: "Oil on Canvas",
    status: "Available",
    price: "5000",
    image: "./images/Composition_With_Mushroom_1.jpg",
    location: "Dubai",
    description: "Composition with Northern Mushrooms 1 mesmerizes with its marriage of simplicity and expressive brushwork, focusing on a singular, substantial mushroom at its core. Dynamic strokes, seemingly chaotic yet purposeful, captivate the viewer, while the artist's technique adds tactile realism to the subject. Rich, varied strokes enhance the mushroom's three-dimensional quality, with earthy tones infusing lifelike semblance. Cool whites in the background create visual balance, drawing attention to intricate details. This interplay of warm and cool hues deepens visual depth, accentuating the mushroom's presence. Celebrating the beauty of nature, the painting's evocative representation showcases mastery of expressive strokes and dimensional appeal."
  },
  {
    id: "a13",
    title: "Composition with Northern Mushrooms 2",
    year: 2023,
    collection: "Portfolio",
    size_cm: "100x80",
    medium: "Oil on Canvas",
    status: "Available",
    price: "5000",
    image: "./images/CompositionWithMushrooms_2.jpg",
    location: "Dubai",
    description: "Composition with Northern Mushrooms 2 intricately portrays a central composition featuring a retro, white plate adorned with an array of distinct mushrooms. Meticulously rendered with unique shapes and colors, each mushroom emerges from the soil-dappled plate, celebrating the diversity found in nature. The earthy color palette evokes the forest floor's natural tones, while the wooden table beneath adds depth and subtlety. Textured with bold strokes, the mushrooms exude tactile presence and individual character. Beyond visual beauty, the painting carries cultural significance, depicting mushroom foraging as a cherished family bonding activity passed down through generations. This rich tapestry captures both visual and cultural dimensions, inviting viewers to connect with shared experiences and traditions."
  },
  {
    id: "a14",
    title: "Crocodile",
    year: 2024,
    collection: "Portfolio",
    size_cm: "250x100",
    medium: "Oil on Canvas",
    status: "Available",
    price: "25000",
    image: "./images/Crocodile.jpg",
    location: "Dubai",
    description: "This painting portrays a crocodile in striking realism, stretched across a 250 × 100 cm canvas. Depicted with meticulous attention to detail, the creature's rough, armored skin is brought to life through a palette of nuanced tones: beige captures the dryness of sunbaked scales, coral subtly warms the underbelly and shadows, while teal pools in the reflections of imagined marsh waters. Indigo weaves through the deeper contours and creases, enhancing the sense of depth and age in the animal's form, and gray ties the composition together, grounding it in stark naturalism. Every scale, claw, and ridge is painted with lifelike precision, presenting the crocodile not as a symbol or metaphor—but as a force of nature, still and silent, yet undeniably powerful."
  },
  {
    id: "a15",
    title: "Danny Reading",
    year: 2023,
    collection: "Portfolio",
    size_cm: "90x60",
    medium: "Oil on Canvas",
    status: "Available",
    price: "6000",
    image: "./images/Danny_Reading.jpg",
    location: "Dubai",
    description: "Danny Reading intricately captures a scene of domestic tranquility in oil-on-canvas. The artist's husband sits on a plush couch, bathed in gentle lamp light, surrounded by arranged pillows and a snug blanket. Light and shadow create striking contrasts, accentuating the artistically rendered, tucked legs. Warm tones infuse the palette, enhancing coziness, while subtle red and violet undertones deepen emotional depth. The relaxed background directs focus to the figure, maintaining its prominence. Drawing elements are purposefully casual, fostering a comfortable atmosphere. This nuanced artwork skillfully balances meticulous technique with artful spontaneity, conveying both physical and emotional dimensions of the intimate moment."
  },
  {
    id: "a16",
    title: "Exhausted",
    year: 2023,
    collection: "Portfolio",
    size_cm: "40x30",
    medium: "Oil on Canvas",
    status: "Available",
    price: "1500",
    image: "./images/Exhausted.jpg",
    location: "Dubai",
    description: "Exhausted captures the raw and vulnerable moment of a young woman overwhelmed by the weight of her emotions. The painting depicts her resting her head on the dining table, her body slumped with a palpable sense of fatigue. Her expression, though subtly shown, speaks volumes—eyes closed in surrender, her features soft yet heavy, as if the pressures of the world have momentarily worn her down. The dining table, usually a place of connection and nourishment, now becomes a silent witness to her mental state.\nBeside her, a vase of sunflowers droops in quiet resignation, their once-vibrant petals wilting under the weight of time, mirroring the woman's exhaustion. The flowers' faded yellow hues contrast with the deeper, muted tones surrounding them, emphasizing the contrast between what once was full of life and the quiet surrender to weariness. The background is simple, yet rich in emotion, with soft brushstrokes that lend the space a sense of melancholy and stillness.\nThe use of light highlights the woman's tired form, casting shadows across the table that echo her sense of being worn thin. This painting speaks to the complexity of mental and emotional fatigue, showing how, sometimes, exhaustion isn't just physical but deeply internal—a poignant reminder of the human need to rest and recover."
  },
  {
    id: "a17",
    title: "Freesias during the Golden Hour",
    year: 2022,
    collection: "Portfolio",
    size_cm: "120x80",
    medium: "Oil on Canvas",
    status: "Available",
    price: "8000",
    image: "./images/Freesias_During_Golden_Hour.jpg",
    location: "Dubai",
    description: "In Freesias During The Golden Hour the artist skillfully portrays a floral reverie illuminated by the warm embrace of twilight. Soft pastels create a visual symphony, with delicate freesias blooming vibrantly against the setting sun's backdrop. A central, textured vase enhances balance, drawing attention to the intricate beauty of the flowers. Full-bloom freesias boast captivating colors, echoing the twilight hues. Graceful stems guide the viewer's gaze, while meticulous brushstrokes capture delicate details and play of light. This artwork is a testament to the artist's mastery in conveying nature's ephemeral beauty and the allure of fleeting moments."
  },
  {
    id: "a18",
    title: "Girl in a Swimsuit",
    year: 2023,
    collection: "Portfolio",
    size_cm: "50x70",
    medium: "Oil on Canvas",
    status: "Available",
    price: "4000",
    image: "./images/Girl_In_SwimSuit.jpg",
    location: "Dubai",
    description: "In Girl in a Swimsuit the artist achieves a delicate balance, akin to graceful sketchwork. The canvas portrays a girl seated by a pool, legs submerged, amidst a warm, sun-soaked ambiance. Burnt orange tones intensify the heat sensation. Linework dominates, resembling a drawing narrative. The green-blue swimsuit harmonizes with the pool's blue shades, hinting at a gentle breeze. The figure, lost in introspection, avoids eye contact, fostering privacy. Refreshing simplicity, devoid of intricate details, enhances the serene moment. 'Girl in a Swimsuit' skillfully captures tranquil poolside essence, evoking warmth and contemplative solitude."
  },
  {
    id: "a19",
    title: "Gladioli and Alstroemeria in the Morning",
    year: 2022,
    collection: "Portfolio",
    size_cm: "120x90",
    medium: "Oil on Canvas",
    status: "Available",
    price: "8000",
    image: "./images/Gladioli_And_Alstroemeria_In_The_Morning.jpg",
    location: "Dubai",
    description: "Gladioli and Alstroemeria in the Morning has contradicting elements that breathe life into a vanilla setting.  The background, painted in shades of pink with accents of yellow, mirrors the hues of a rising sun, infusing the scene with a warm, morning glow. To add an intriguing edge to the composition, charcoal introduces a subtle contrast. The use of \"dirty\" greens, varied in tone, enhances the realistic quality of the painting, grounding the floral elegance in an earthy context. The canvas comes alive with a vibrant interplay of light and color, as pastels and deeper tones, seemingly contradictory, converge to form a harmonious balance."
  },
  {
    id: "a20",
    title: "Green Apples",
    year: 2023,
    collection: "Portfolio",
    size_cm: "60x45",
    medium: "Oil on Canvas",
    status: "Available",
    price: "3000",
    image: "./images/Green_Apples.jpg",
    location: "Dubai",
    description: "In the painting titled Green Apples a serene composition captures the crisp, natural beauty of its subject. Dominated by shades of green, the artwork radiates freshness, simplicity, and harmony, drawing viewers into its calming presence. At the center, an apple is cut in half, its pale interior revealed with delicate detail and subtle elegance. The seeds, nestled at its core, add a touch of earthy brown, subtly breaking the green palette and grounding the composition.\nThe outer skin of the apple, with its glossy texture and vibrant green hue, reflects the light softly, giving the fruit a lifelike and inviting quality. The green tones range from the apple's bright, fresh skin to muted, mossy shades in the background, creating a harmonious interplay of color that evokes a sense of calm, natural purity, and quiet vibrancy.\nThe composition is minimalistic yet vibrant, inviting viewers to appreciate the understated elegance of a simple moment—a slice of fruit poised in quiet beauty. The painting celebrates the everyday object with an artistic lens, turning a humble apple into a study of freshness, light, and texture. It's a visual ode to the subtle vibrancy of nature, the timeless charm of simplicity, and the fleeting beauty found in ordinary moments."
  },
  {
    id: "a21",
    title: "Green Shoes",
    year: 2023,
    collection: "Portfolio",
    size_cm: "80x40",
    medium: "Oil on Canvas",
    status: "Available",
    price: "3000",
    image: "./images/Green_Shoes.jpg",
    location: "Dubai",
    description: "Green Shoes and Red Shoes is a compelling narrative around a pair of shoes, symbolizing unique life journey. The differences in tones with contrasting pinks, blues, purples, greens and reds mirror life's complexities and signifies individuality and hidden stories within paths."
  },
  {
    id: "a22",
    title: "Hand Holding a Tangerine",
    year: 2024,
    collection: "Portfolio",
    size_cm: "43x43",
    medium: "Oil on Canvas",
    status: "Available",
    price: "2000",
    image: "./images/Hand_with_Clementine.png",
    location: "Dubai",
    description: "Hand Holding a Tangerine is a painting that evokes a sense of quiet intimacy and connection between the human form and nature's vibrant bounty. The canvas is washed in soft white tones, creating an almost ethereal backdrop that allows the central figure—the hand—holding a tangerine, to emerge as the focal point. The hand is depicted in a graceful and yet purposeful manner, fingers gently cupping the fruit, its stem held delicately at the top, offering a sense of care and reverence. The tangerine itself bursts with vivid orange, its color standing out against the pale background with a warm, almost glowing intensity. This careful contrast between the white and the vibrant orange symbolizes a moment of balance—between the calm of human touch and the radiant energy of life's simplest pleasures. The brushwork is soft yet deliberate, capturing the smooth texture of the hand while allowing the tangerine's contours to appear almost tactile, as though one could reach out and feel its natural beauty. The piece invites contemplation on the fragility and fleeting nature of everyday moments, emphasizing how a simple gesture, like holding a piece of fruit, can become a profound expression of life's delicate balance between nature and humanity."
  },
  {
    id: "a23",
    title: "He Loves Me (Not)",
    year: 2023,
    collection: "Portfolio",
    size_cm: "60x80",
    medium: "Oil on Canvas",
    status: "Available",
    price: "5000",
    image: "./images/He_Loves_Me_Not.jpg",
    location: "Dubai",
    description: "In He Loves Me (Not) , a touching portrait unfolds: a girl delicately cradles a daisy, pondering if her affection is returned. Her expression, a mix of uncertainty and longing, mirrors the ache of unreciprocated love. Around her, daisies drift, embodying countless opportunities to discover love. The painting captures the emotional essence of love's uncertainties, where every moment is a chance for connection yet carries the weight of potential heartache. It's a timeless portrayal of longing, resilience, and the enduring quest for emotional fulfillment amidst life's fleeting possibilities."
  },
  {
    id: "a24",
    title: "Iris 1",
    year: 2023,
    collection: "Portfolio",
    size_cm: "35x28",
    medium: "Oil on Canvas",
    status: "Available",
    price: "1000",
    image: "./images/Iris_1.jpg",
    location: "Dubai",
    description: "In the painting titled Iris, a mesmerizing interplay of colors brings the iconic flower to life with elegance and vibrancy. The canvas is awash with hues of green, blue, purple, and yellow, forming a harmonious symphony of contrasts. The petals of the iris, rendered in rich, velvety purple with hints of deep blue, unfurl gracefully, capturing the flower's delicate yet striking beauty. Golden yellow accents at the bloom's core radiate warmth, drawing the eye and symbolizing vitality and hope. The surrounding leaves and stems, painted in lush, vivid greens, frame the flower with a sense of natural elegance, their vertical lines adding a sense of movement and life. The background shifts through gradients of soft blues and greens, reminiscent of a tranquil garden on a sunlit morning, providing a serene contrast that allows the iris to command attention. Dynamic yet refined brushstrokes convey the texture and energy of the flower, imbuing it with a sense of vitality and timelessness. Iris is a visual celebration of the beauty and harmony found in nature, inviting viewers to pause and reflect on the delicate balance of colors, forms, and emotions embodied by this stunning bloom. It's a radiant ode to the fleeting yet profound beauty of life."
  },
  {
    id: "a25",
    title: "Iris 2",
    year: 2023,
    collection: "Portfolio",
    size_cm: "35x28",
    medium: "Oil on Canvas",
    status: "Available",
    price: "1000",
    image: "./images/Iris_2.jpg",
    location: "Dubai",
    description: "In the painting titled Iris, a mesmerizing interplay of colors brings the iconic flower to life with elegance and vibrancy. The canvas is awash with hues of green, blue, purple, and yellow, forming a harmonious symphony of contrasts. The petals of the iris, rendered in rich, velvety purple with hints of deep blue, unfurl gracefully, capturing the flower's delicate yet striking beauty. Golden yellow accents at the bloom's core radiate warmth, drawing the eye and symbolizing vitality and hope. The surrounding leaves and stems, painted in lush, vivid greens, frame the flower with a sense of natural elegance, their vertical lines adding a sense of movement and life. The background shifts through gradients of soft blues and greens, reminiscent of a tranquil garden on a sunlit morning, providing a serene contrast that allows the iris to command attention. Dynamic yet refined brushstrokes convey the texture and energy of the flower, imbuing it with a sense of vitality and timelessness. Iris is a visual celebration of the beauty and harmony found in nature, inviting viewers to pause and reflect on the delicate balance of colors, forms, and emotions embodied by this stunning bloom. It's a radiant ode to the fleeting yet profound beauty of life."
  },
  {
    id: "a26",
    title: "Iris 3",
    year: 2023,
    collection: "Portfolio",
    size_cm: "35x28",
    medium: "Oil on Canvas",
    status: "Available",
    price: "1000",
    image: "./images/Iris_3.jpg",
    location: "Dubai",
    description: "In the painting titled Iris, a mesmerizing interplay of colors brings the iconic flower to life with elegance and vibrancy. The canvas is awash with hues of green, blue, purple, and yellow, forming a harmonious symphony of contrasts. The petals of the iris, rendered in rich, velvety purple with hints of deep blue, unfurl gracefully, capturing the flower's delicate yet striking beauty. Golden yellow accents at the bloom's core radiate warmth, drawing the eye and symbolizing vitality and hope. The surrounding leaves and stems, painted in lush, vivid greens, frame the flower with a sense of natural elegance, their vertical lines adding a sense of movement and life. The background shifts through gradients of soft blues and greens, reminiscent of a tranquil garden on a sunlit morning, providing a serene contrast that allows the iris to command attention. Dynamic yet refined brushstrokes convey the texture and energy of the flower, imbuing it with a sense of vitality and timelessness. Iris is a visual celebration of the beauty and harmony found in nature, inviting viewers to pause and reflect on the delicate balance of colors, forms, and emotions embodied by this stunning bloom. It's a radiant ode to the fleeting yet profound beauty of life."
  },
  {
    id: "a27",
    title: "Lemons",
    year: 2023,
    collection: "Portfolio",
    size_cm: "50x60",
    medium: "Oil on Canvas",
    status: "Available",
    price: "4000",
    image: "./images/Lemons.jpg",
    location: "Dubai",
    description: "In this painting duo, the citrus fruits have golden yellows echoing the sun's warmth, as well as shades of bright oranges and burnt browns. These warm tones intensify the summer heat and haze, creating an atmosphere that feels almost tangible. Dynamic brushstrokes add movement and energy, infusing the compositions with life. The contrast between the simple yet vivid fruits and the nuanced background creates a delicate interplay, inviting viewers to savor the sensory richness of a sun-kissed summer day."
  },
  {
    id: "a28",
    title: "Lemons in a Net",
    year: 2024,
    collection: "Portfolio",
    size_cm: "120x150",
    medium: "Oil on Canvas",
    status: "Available",
    price: "12000",
    image: "./images/Lemons_In_A_Net.jpg",
    location: "Dubai",
    description: "A cluster of lemons rests inside a fine mesh net—vibrant, full of light, and gently pressing against their boundaries. The translucent net gathers rather than restrains, shaping the composition with quiet tension and balance. Each lemon touches another, forming a moment of stillness, connection, and potential.\nThis work invites reflection on structure and freedom, intimacy and individuality. The net becomes a metaphor not for limitation, but for gentle order—suggesting that what holds us can also support us. Bright, ordinary forms take on quiet symbolism, transforming still life into a meditation on coexistence and form.\n"
  },
  {
    id: "a29",
    title: "Lilies in Summer",
    year: 2023,
    collection: "Portfolio",
    size_cm: "52x76",
    medium: "Oil on Canvas",
    status: "Available",
    price: "4000",
    image: "./images/Lilies_In_Summer.jpg",
    location: "Dubai",
    description: "In Lilies in the Summer, The choice of color radiates warmth without overpowering the ethereal nature of the floral subject. Daring brushstrokes dominate the piece, contributing to its dynamic and lively character. With only a few carefully placed details, the painting achieves a remarkable sense of spontaneity and life. \"Lilies in the Summer\" stands as a testament to the bold approach, where daring brushwork and a selective focus on movement capture the essence of a summer bouquet in full bloom, celebrating the fleeting beauty of nature."
  },
  {
    id: "a30",
    title: "Limitless",
    year: 2022,
    collection: "Portfolio",
    size_cm: "100x120",
    medium: "Oil on Canvas",
    status: "Available",
    price: "5000",
    image: "./images/Limitless.jpg",
    location: "Dubai",
    description: "Everything starts from childhood - dreams and ambitions, but most importantly- the future. Children carry on the collective memory of their ancestors, and enrich it by adding their own experiences to it. This painting is about remembering the heritage, respecting the past, but also reaching for the stars and not being afraid to push the borders.\n\nMany of the UAE's achievements are known worldwide, and many are yet to come. Perhaps one of the children that is depicted on the painting is the one to design the new tallest building on the globe, or the first woman to go on an expedition to Mars.  The children are presented not as people who need to learn about the world, but rather as the ones that will lead nations and sculpt the future. They are fearless, imaginative and strive for more. Some children say and do the most unexpected things, and have the most incredible ideas that an adult would never think of. They are bold, and curious to see what the universe has to offer. This is captured in the girl's personality, she is a dreamer who knows what she wants and is not giving up. The boy's character is a lot more reserved, thoughtful, a true mathematician. He is carefully adding sand blocks, making sure the \"building\" doesn't fall.  He is a visionary and finds inspiration in nature.\n\nThe setting of the painting is the beach, as the sea green-blue and sandy ochres create a pleasant combination of colors and have a direct association with timelessness and serenity. Also, the beach is the place where children love to play, build sandcastles and it serves as a reference to a \"happy place\" in many of adults' memories. The light is coming from the top, like it would be around 12pm, hinting that the sun is there to give visibility and light to all future discoveries and achievements. The colors are vivid with dramatic shadows to emphasize the direction of the light. The painting includes some cultural elements like the colors of the UAE flag, the boy's clothes and the little toy camels in the bucket, suggesting that no matter how far the progress may go, there will always be a traditional flavor in the society.\n\nThe technique is a mixture of two amazing art schools, Russian and Italian. The Russian technique is light and airy. Italian, on the other hand, is about contrast and browns. Merging the two helped me achieve the effortless atmosphere and have beautiful flesh tones. Some modern effects give the painting an interesting twist, as if they happened by accident."
  },
  {
    id: "a31",
    title: "Mixed signals",
    year: 2023,
    collection: "Portfolio",
    size_cm: "50x100",
    medium: "Oil on Canvas",
    status: "Available",
    price: "7000",
    image: "./images/Mixed_Signals.jpg",
    location: "Dubai",
    description: "Mixed Signals features two portraits that convey a complex narrative. The woman leans in with an expression of adoration, her gaze fixed on the man who appears lost in contemplation, looking away. This juxtaposition symbolizes the clash between one's intentions and inner thoughts. The background, painted in a blend of warm red and cool blue to create purple, reinforces this duality. It represents the conflicting emotions and desires within us, where warmth meets coolness, passion meets reservation. \"Mixed Signals\" invites viewers to ponder the intricacies of human connection, the ambiguity of emotions, and the enigmatic nature of relationships."
  },
  {
    id: "a32",
    title: "Monkeys Everywhere - The Dance of Instinct",
    year: 2025,
    collection: "Portfolio",
    size_cm: "120x60",
    medium: "Oil on Canvas",
    status: "Available",
    price: "9000",
    image: "./images/MonkeysEverywhere.jpg",
    location: "Dubai",
    description: "In Monkeys Everywhere - The Dance of Instinct the viewer is drawn into a vivid, almost surreal arboreal world—where chaos and harmony coexist. The fiery orange backdrop, with its swirling patterns of red and ember-like foliage, evokes not just a forest, but the primal energy of life itself. This infernal palette could symbolize the untamed forces of nature or the inner fire of consciousness, both beautiful and relentless. The four monkeys, scattered across the canvas, each embody a different aspect of existence and awareness. One monkey strides purposefully across the top, representing action and progress—the ceaseless march forward. Another sits still, contemplative, perhaps symbolizing awareness, observation, and the fleeting stillness in life's constant motion.\nThe two monkeys entangled and hanging upside down evoke play, chaos, and interconnection. Their inversion from the norm suggests the unpredictable nature of existence and the duality of experience—joy and struggle, freedom and entrapment. Their mirrored postures also reflect the human tendency to see oneself in others, perhaps a meditation on identity and empathy. Overall, the painting becomes an allegory for the human condition, with the monkeys acting as stand-ins for our own restless minds—forever swinging between past and future, action and reflection, instinct and understanding. Amid the vivid intensity of their world, there's a quiet message: that even in the wildest of places, meaning can be found—not in stillness, but in movement."
  },
  {
    id: "a33",
    title: "More Passion",
    year: 2023,
    collection: "Portfolio",
    size_cm: "70x90",
    medium: "Oil on Canvas",
    status: "Available",
    price: "7000",
    image: "./images/More_Passion.jpg",
    location: "Dubai",
    description: "More Passion is immersed entirely in hues of red, evoking a sense of intensity and excitement. At its heart, a woman extends her arms, covered with either red paint or gloves that seamlessly merge into her skin tone. The transition signifies a fusion of passion with the essence of self. Her hands, textured with bold, impulsive strokes, symbolize the raw energy and vitality of passionate actions. Hands, being our primary explorers of the world, convey sensitivity and expressiveness, capturing the essence of human connection and the profound depth of emotions conveyed through touch. The painting celebrates the vibrant dynamism of passion, embracing its transformative power in our lives."
  },
  {
    id: "a34",
    title: "Morning Coffee",
    year: 2024,
    collection: "Portfolio",
    size_cm: "80x60",
    medium: "Oil on Canvas",
    status: "Available",
    price: "7000",
    image: "./images/Morning_Coffee.jpg",
    location: "Dubai",
    description: "Morning Coffee is not just a portrait of one woman, but of all women. It captures a universal ritual—the quiet act of preparing to face the world. The mud mask becomes more than skincare; it's symbolic armor, a gesture of care, transformation, and control. Even in solitude, even before the day begins, there is intention: to be ready, to be presentable, to carry oneself with dignity. The painting reflects the emotional labor behind composure—the internal strength required to present a calm surface despite whatever might lie beneath. The red mug, warm and vibrant, becomes a metaphor for energy, identity, and the fire held within. This is a portrait of quiet resilience. A reminder that strength often starts in the smallest of rituals—and that behind every polished face is a woman who chose to begin again.\n\n."
  },
  {
    id: "a35",
    title: "Peeled Clementine in the Sun",
    year: 2023,
    collection: "Portfolio",
    size_cm: "61x76",
    medium: "Oil on Canvas",
    status: "Available",
    price: "4000",
    image: "./images/Peeled_Clementine.jpg",
    location: "Dubai",
    description: "In Peeled Clementine in the Sun the artist delves into a rich exploration of textures, drawing inspiration from diverse elements within the composition. A mandarin, centrally positioned and dramatically lit, casts its form predominantly in shadow, creating a captivating interplay of light and dark. Surrounding fabrics envelop the subject, enhancing visual richness and adding a sense of coziness. Warm and cool tones heighten tactile quality, contrasting the smoothness of the fruit with textural intricacies. This painting showcases the artist's mastery in creating a harmonious symphony of textures, colors, and lighting, transforming a simple subject into an engaging visual experience."
  },
  {
    id: "a36",
    title: "Peonies",
    year: 2023,
    collection: "Portfolio",
    size_cm: "40x30",
    medium: "Oil on Canvas",
    status: "Available",
    price: "1000",
    image: "./images/Peonies.jpg",
    location: "Dubai",
    description: "In the painting titled Peonies, a lush bouquet of blooming peonies takes center stage, capturing the delicate beauty and elegance of these beloved flowers. The soft interplay of green, pink, white, and beige creates a harmonious and serene palette that exudes femininity and tranquility. The petals, painted in various shades of pink—from pale blush to deep rose—are layered with gentle, flowing brushstrokes, evoking the lush, velvety texture of the blossoms. Hints of white accentuate their softness, adding a sense of freshness and light to the composition. The foliage, depicted in shades of vibrant and muted green, forms a verdant backdrop that highlights the vividness of the flowers. The green tones, ranging from emerald to moss, create depth and balance, grounding the airy blooms in natural elegance. The beige undertones subtly weave through the painting, suggesting a warm, neutral foundation that ties the composition together. Light filters across the canvas, casting subtle highlights and shadows that bring the peonies to life, their petals seemingly glowing with an inner radiance.  Peonies is a celebration of natural beauty and fleeting grace, inviting viewers to savor the timeless charm of blooming flowers and the quiet moments they inspire. It's a gentle ode to life's delicate joys."
  },
  {
    id: "a37",
    title: "Pink Tulips",
    year: 2023,
    collection: "Portfolio",
    size_cm: "61x76",
    medium: "Oil on Canvas",
    status: "Available",
    price: "4000",
    image: "./images/Pink_Tulips.jpg",
    location: "Dubai",
    description: "In Pink Tulips the canvas bursts with the delicate beauty of spring blooms. A bouquet of vibrant pink tulips stands tall within a graceful vase, their slender stems reaching upward with a sense of natural elegance. The artist's brushstrokes capture the softness of the petals and the verdant greenery of the leaves with a gentle touch. Light dances across the scene, casting subtle highlights and shadows that lend depth and dimension to the composition. "
  },
  {
    id: "a38",
    title: "Red Gladioli",
    year: 2023,
    collection: "Portfolio",
    size_cm: "40x30",
    medium: "Oil on Canvas",
    status: "Available",
    price: "1000",
    image: "./images/Red_Gladioli.jpg",
    location: "Dubai",
    description: "In the painting titled Red Gladioli, the striking elegance of gladiolus blooms is brought to life with a vivid contrast of red and white tones. The gladioli, rendered in rich, fiery shades of red, dominate the composition, with their long, slender stems and blossoms exuding a sense of boldness, vitality, and natural elegance. The red hues, ranging from deep crimson to vibrant scarlet, embody passion, strength, vibrancy, and emotional intensity, creating a dynamic focal point that draws the viewer's attention immediately. The background, which is a serene expanse of soft white, enhances the vividness of the flowers while evoking a sense of purity, calm, and simplicity. The interplay between the vibrant reds and the stark white backdrop creates a dramatic and yet harmonious composition, emphasizing the sculptural beauty of the gladioli blossoms. Delicate highlights trace the petals, capturing their natural texture and the way light dances across their surfaces with gentle fluidity and brilliance. The stems, a subtle green, provide a grounding element, adding a hint of nature's freshness amidst the bold contrast of colors. Red Gladioli is a celebration of nature's resilience, beauty, and vibrant contrasts, a tribute to the flower's symbolism of strength, remembrance, grace, and enduring vitality."
  },
  {
    id: "a39",
    title: "Red Shoes",
    year: 2023,
    collection: "Portfolio",
    size_cm: "80x40",
    medium: "Oil on Canvas",
    status: "Available",
    price: "3000",
    image: "./images/Red_Shoes.jpg",
    location: "Dubai",
    description: "Green Shoes and Red Shoes is a compelling narrative around a pair of shoes, symbolizing unique life journey. The differences in tones with contrasting pinks, blues, purples, greens and reds mirror life's complexities and signifies individuality and hidden stories within paths."
  },
  {
    id: "a40",
    title: "Strength of Spirit 1",
    year: 2024,
    collection: "Portfolio",
    size_cm: "120x60",
    medium: "Oil on Canvas",
    status: "Available",
    price: "10000",
    image: "./images/Strength_Of_The_Spirit_1.jpg",
    location: "Dubai",
    description: "Strength of Spirit 1 captures the essence of legacy through its powerful portrayal of resilience, determination, and inner strength. In this dynamic piece, a fearless female boxer commands attention, embodying not only physical grit but also the values and convictions that define a meaningful life. Her stance, poised for battle, reflects her willingness to face challenges head-on, inspiring those who follow her example to rise above their own struggles. The painting goes beyond the surface of combat, delving into the profound legacy of self-improvement and perseverance. Through her fight, the boxer symbolizes the timeless lessons of overcoming limitations, embracing growth, and demonstrating the strength of character needed to triumph over adversity. Her unwavering spirit reminds viewers of the values we pass down to future generations: the courage to stand up for what we believe in, the resolve to pursue our dreams, and the importance of facing life's challenges with grace and tenacity. Strength of Spirit 1 serves as a visual metaphor for the legacy we leave behind—not just through our victories, but through the way we live our values every day. It inspires viewers to embody the virtues of determination and resilience, ensuring that these lessons endure as a source of pride and motivation for generations to come."
  },
  {
    id: "a41",
    title: "Strength of Spirit 2",
    year: 2024,
    collection: "Portfolio",
    size_cm: "120x60",
    medium: "Oil on Canvas",
    status: "Available",
    price: "10000",
    image: "./images/Strength_Of_The_Spirit_2.jpg",
    location: "Dubai",
    description: "Strength of Spirit 2 depicts an unwrapping of resilience and vulnerability. The painting captures a fighter with a black eye, a visible testament to past wounds and bravery. Yet, the deeper narrative unfolds as the fighter chooses to reveal sensitivity, symbolized by letting down his guard and exposing his essence. This act of openness contrasts with the toughness of the fighter, illustrating that strength isn't always about physical power but also about courage in vulnerability. The black eye becomes a symbol of endurance and the choice to remain sensitive despite life's challenges. It's a visual exploration of the multifaceted nature of strength, inspiring viewers to embrace their inner resilience and authenticity."
  },
  {
    id: "a42",
    title: "Summer",
    year: 2023,
    collection: "Portfolio",
    size_cm: "80x60",
    medium: "Oil on Canvas",
    status: "Available",
    price: "4000",
    image: "./images/Summer.jpg",
    location: "Dubai",
    description: "In Summer an oil on canvas painting, a serene coastal scene unfolds as a girl relaxes at a seaside café near a pristine white castle overlooking the sea. Meticulous attention to detail captures the essence of a leisurely summer day. The vibrant table, reminiscent of Mediterranean tiles, adds local charm. The girl, in a sun-shielding hat and white dress, exudes a breezy sensation with blue outlines hinting at a coastal breeze. Her hidden eyes evoke mystery, inviting contemplation. Summer is a sensory celebration, inviting viewers to bask in warmth, feel the seaside breeze, and immerse themselves in tranquil contemplation."
  },
  {
    id: "a43",
    title: "Sunday Brunch",
    year: 2024,
    collection: "Portfolio",
    size_cm: "150x75",
    medium: "Oil on Canvas",
    status: "Available",
    price: "10000",
    image: "./images/Sunday_Brunch.jpg",
    location: "Dubai",
    description: "Scattered plates, empty cups, and the remains of a shared meal float in a dark, textured space—echoes of conversation, ritual, and pause. The overhead perspective invites quiet observation, as though the viewer has arrived just after everyone has left, the warmth of presence still lingering in the arrangement. Each object feels deliberate: the tea steeping with lemon, the half-eaten bread roll, the upturned forks resting on napkins. These small, familiar details capture the aftermath of connection, the beauty in the ordinary. There is no central figure, but presence is everywhere—felt in the used dishes, in the balanced composition, in the absence that speaks of fullness. Symbolically, Sunday Brunch becomes a meditation on time held gently—on the moments between events, where meaning gathers slowly and without urgency. The scene speaks of togetherness, routine, and the quiet poetry of shared spaces. What remains on the table is not just food, but memory—unfinished, imperfect, and fully human.."
  },
  {
    id: "a44",
    title: "Sunflower Field 2",
    year: 2023,
    collection: "Portfolio",
    size_cm: "80x80",
    medium: "Oil on Canvas",
    status: "Available",
    price: "7000",
    image: "./images/Sunflower_Field_2.jpg",
    location: "Dubai",
    description: "In Sunflower Field 2 an evocative oil on canvas creation, the artist ventures into the realm of symbolism, drawing inspiration from the Bulgarian band Ostava to craft a narrative rich in metaphor and allegory. Figures within the field reach toward the sun or conceal themselves amidst vibrant sunflowers, their legs peeking through the blossoms. Aesthetic deformation of the bodies enhances the symbolic representation of flowers, pushing boundaries of form for deeper meaning. Sunflowers dominate the composition, overshadowing figures, while dramatic movements inject dynamism. Unconventional yellow skies add to the hazy, still atmosphere of a scorching summer. This piece prompts reflection on human existence within the boundless beauty and challenges of a sunflower field."
  },
  {
    id: "a45",
    title: "Sunflowers at Noon",
    year: 2022,
    collection: "Portfolio",
    size_cm: "90x60",
    medium: "Oil on Canvas",
    status: "Available",
    price: "3000",
    image: "./images/Sunflowers_At_Noon.jpg",
    location: "Dubai",
    description: "In Sunflowers at Noon an engaging oil on canvas piece, the artist offers a fresh interpretation of the iconic theme, imbuing it with her distinctive style. Bold oranges and ochres juxtapose against a pristine white vase and warm green leaves, creating a visually striking contrast. Eschewing precision for raw strokes and charcoal, the artwork exudes authenticity and expressiveness. Sunflowers, rendered with vitality, capture the essence of a sunlit noon. Absence of intricate details invites visceral engagement, conveying raw emotions. This bold approach revitalizes a familiar theme, crafting a dynamic composition resonant with the warmth and vibrancy of midday sun."
  },
  {
    id: "a46",
    title: "The Impact",
    year: 2024,
    collection: "Portfolio",
    size_cm: "60x60",
    medium: "Oil on Canvas",
    status: "Available",
    price: "5000",
    image: "./images/The_Impact.png",
    location: "Dubai",
    description: "Two fighters are locked in a moment of physical intensity—one striking, the other absorbing. Muscles tighten, bodies twist, and within this single frame, time seems to hold its breath. The circular canvas heightens the sense of enclosure, drawing the viewer into a world where force, focus, and fatigue converge. This is not just about sport or violence—it's about the emotional weight behind confrontation. The red glove lands with purpose, but the deeper impact is not only physical. There's something almost tender in the vulnerability of the figure who receives the blow—head lowered, body exposed, but still standing. The Impact explores the duality of strength and fragility. It's about the roles we take on in conflict, the moments where control shifts, and how those moments leave a mark—seen and unseen. Whether read as a literal fight or a metaphor for struggle, the piece asks us to consider what it means to endure, to resist, and to respond."
  },
  {
    id: "a47",
    title: "The Missed Opportunity",
    year: 2024,
    collection: "Portfolio",
    size_cm: "45x90",
    medium: "Oil on Canvas",
    status: "Available",
    price: "5000",
    image: "./images/The_Missed_Opportunity.jpg",
    location: "Dubai",
    description: "The Missed Opportunity speaks to more than the dynamics of combat. It explores the fragility of timing, the thin line between success and failure, action and inaction. The energy in the gesture remains, but its purpose dissolves. What's left is a portrait of effort unmet, of anticipation unfulfilled. Outlined in violet, the figures glow with a kind of inner friction—as if haunted by the electricity of what could have been. This subtle halo sets them apart from the blurred crowd and background, emphasizing the emotional isolation within a shared space of competition. On a symbolic level, the painting mirrors the missed chances we carry—words not said, moments not seized, paths not taken. It reminds us that power alone does not guarantee outcome, and that sometimes, what lingers most deeply is not the hit, but the absence of it."
  },
  {
    id: "a48",
    title: "The Running Dachshund",
    year: 2024,
    collection: "Portfolio",
    size_cm: "250x100",
    medium: "Oil on Canvas",
    status: "Available",
    price: "25000",
    image: "./images/The_Running_Daschund.jpg",
    location: "Dubai",
    description: "Running Dachshund captures more than a playful sprint—it becomes a symbol of persistence, lightness, and the freedom found in forward momentum. The exaggerated elongation of the body, almost surreal, emphasizes endurance in the face of limitation. It's a portrait of optimism in motion: determination without tension, movement without resistance. This is not simply a dog in a field—it's the spirit of uninhibited joy. A reminder that life's greatest moments may come not from the destination, but from the run itself: wild, focused, and utterly free."
  },
  {
    id: "a49",
    title: "The Silent Sentinel",
    year: 2025,
    collection: "Portfolio",
    size_cm: "80x80",
    medium: "Oil on Canvas",
    status: "Available",
    price: "8000",
    image: "./images/The_Silent_Sentinel.jpg",
    location: "Dubai",
    description: "The Silent Sentinel stands as a symbol of stoic endurance, watching over a desolate yet vibrant landscape. The cactus's vivid blooms offer a delicate contrast to its armored form, while the red shadow suggests unseen depth—perhaps of past struggles or protective energy. Surrounded by emptiness, the sentinel remains grounded, a reminder that strength often resides in stillness and survival is a quiet form of resistance."
  },
  {
    id: "a50",
    title: "Too Early",
    year: 2023,
    collection: "Portfolio",
    size_cm: "80x80",
    medium: "Oil on Canvas",
    status: "Available",
    price: "7000",
    image: "./images/Too_Early.jpg",
    location: "Dubai",
    description: "Too Early captures a profound moment of introspection and vulnerability. The painting portrays a girl enveloped in her blanket, symbolizing her comfort zone and introverted nature. Like a cocoon, the blanket represents safety but also the reluctance to venture beyond familiar territory. The artwork delves into the complexities of trust and intentions, as the girl wonders if it's too early to let someone in, to reveal her true self. It's a visual meditation on the gradual process of getting to know someone, of earning trust and understanding genuine intentions. The painting invites viewers to contemplate the delicate balance between comfort and growth, between guarding oneself and opening up to meaningful connections."
  },
  {
    id: "a51",
    title: "Tulip and Dragonfruit",
    year: 2023,
    collection: "Portfolio",
    size_cm: "40x50",
    medium: "Oil on Canvas",
    status: "Available",
    price: "2500",
    image: "./images/Tulip_And_Dragonfruit.jpg",
    location: "Dubai",
    description: "In this painting titled Tulip and Dragonfruit, a delicate balance of colors and textures captures the essence of nature's quiet elegance. At the heart of the composition, a striking dragonfruit stands out with its vibrant reddish-pink hue, its leathery skin and intricate patterns adding depth and richness to the scene. Its bold color contrasts beautifully with the soft, muted beige background, creating a sense of warmth and tranquility. Surrounding the dragonfruit, a cluster of pink tulips rises with gentle grace. Their soft petals unfurl, their pink tones varying in shades from pale blush to a deeper, almost magenta hue, adding a sense of vibrancy and life to the painting. The tulips' slender stems and delicate curves are rendered with a light touch, evoking a sense of fragility and softness. The smooth, muted beige tones of the background complement the colors of the tulips and dragonfruit, creating a serene atmosphere that invites the viewer to appreciate the quiet beauty of nature's more subtle moments. The painting captures the harmony between the fruit's exotic intensity and the tulips' gentle elegance, highlighting the contrasts between boldness and delicacy, warmth and coolness. It's a visual celebration of the vibrant richness and calm simplicity of nature, evoking both a sense of freshness and timeless beauty."
  },
  {
    id: "a52",
    title: "Turquoise Hat",
    year: 2023,
    collection: "Portfolio",
    size_cm: "60x50",
    medium: "Oil on Canvas",
    status: "Available",
    price: "25000",
    image: "./images/Turquoise_Hat.jpg",
    location: "Dubai",
    description: "In Turquoise Hat an entrancing oil on canvas painting, the artist deftly channels impressionist influences to capture the tranquil beauty of twilight. Centered around a young girl in a swimsuit on a striped towel, the scene unfolds during the magical transition from day to night. Soft hues inspired by impressionism, including purples, lavenders, and peachy mid-tones, create an ethereal atmosphere. A vivid turquoise hat commands attention amidst the subtle palette. The girl's direct gaze fosters intimacy, while the background's deep green complements her form. This thoughtful composition evokes comfort and tranquility, inviting viewers to immerse themselves in twilight's serene beauty."
  },
  {
    id: "a53",
    title: "Winterberry",
    year: 2023,
    collection: "Portfolio",
    size_cm: "60x60",
    medium: "Oil on Canvas",
    status: "Available",
    price: "3000",
    image: "./images/Winterberry.png",
    location: "Dubai",
    description: "In this painting, winterberries come to life against a tranquil, snow-dusted backdrop, capturing the serene beauty of the colder months. The scene is dominated by clusters of vibrant red berries, their deep hue standing out in stark contrast to the muted tones of the surrounding branches and snow. The delicate, winding brown branches stretch across the canvas, their twists and turns evoking the quiet elegance of winter's skeletal trees. The berries, glistening with frost, appear almost weightless, adding a pop of color to the otherwise subdued, monochromatic scene. The predominant white hues of the canvas represent the purity of fresh snow and the stillness of winter's embrace. Soft brushstrokes of white blend across the background, creating a soft, ethereal effect that gives the painting a sense of peaceful quiet. The snow seems to envelop the berries, their vibrant red tones standing as beacons of life and color in the midst of winter's calm. This painting beautifully conveys the resilience and quiet strength of nature during the colder months. The stark simplicity of the composition is both peaceful and captivating, inviting the viewer to pause and reflect on the delicate beauty found in the small, often overlooked moments of nature. The winterberries symbolize the endurance of life amidst the chill and stillness of winter."
  },
  {
    id: "a54",
    title: "Yellow Alstroemeria",
    year: 2023,
    collection: "Portfolio",
    size_cm: "60x60",
    medium: "Oil on Canvas",
    status: "Available",
    price: "3000",
    image: "./images/Yellow_Alstoemeria.jpg",
    location: "Dubai",
    description: "In this painting, yellow alstroemeria blooms boldly against a backdrop of contrasting colors. The upper part of the background is a serene blue-grey, reminiscent of a tranquil sky, while the lower portion transitions into a deep, dark green, evoking the lushness of nature. This horizontal divide creates a striking visual contrast, symbolizing the interplay between serenity and vitality, calmness and vibrancy. The alstroemeria, with its cheerful yellow petals, serves as a beacon of brightness amid the contrasting tones, drawing the eye and infusing the composition with a sense of dynamic balance. It's a visual metaphor for finding beauty and harmony in life's diverse elements."
  }
];
